# Generated by Django 5.0.7 on 2024-08-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bar', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_supermercado.products')),
            ],
        ),
    ]
